### ISSUE TITLE
Remove console.log('out') in production build.

### ISSUE THREAD

**Issue by twickstrom** [angeliquekom/vue-json-to-csv#5]
**Describe the bug**
The distribution file contains a console.log statement. This should be removed. dist/vue-json-to-csv.js?251c:1

**To Reproduce**
1. Execute a new json-to-csv
2. Look in the console to see the console.log('out') statement

**Expected behavior**
Console.log sttatements should not be in production builds.

**Screenshots**
<img width="1438" alt="screen shot 2018-11-11 at 8 09 05 pm" src="https://user-images.githubusercontent.com/775346/48322541-b6b31680-e5ed-11e8-8c9e-2ebe6e2a669c.png">

**Comment by lefterisnik** [comment]
+1

**Comment by angeliquekom** [comment]
@twickstrom Thanks for checking that. I have fixed that issue at the new version 1.1.7.
