### ISSUE TITLE
# within JSON Object seems stops conversion and produces incomplete csv file

### ISSUE THREAD

**Issue by tim4vt** [angeliquekom/vue-json-to-csv#7]
Having a # within the JSON Object I am converting causes the conversion to stop immediately and gives me a incomplete CSV file

As example I have added a # in the task_description within the JSON Object and you can see in the csv file the conversion stopped there. Please see the following sandbox to reproduce the error:
https://codesandbox.io/embed/8koplpy6q0

**Comment by angeliquekom** [comment]
Thanks @tim4vt! Good catch! The issue was occured because I was using encodeURI which blocks special characters. I replaced it with encodeURIComponent. I releaded version 1.1.8 for fixing the bug.
